server:
  port: 8001

spring:
  application:
    name: gateway-service

  # Nacos配置
  cloud:
    nacos:
      discovery:
        namespace: public
        group: DEFAULT_GROUP
      config:
        enabled: false
        import-check:
          enabled: false

    # Gateway配置
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
        - id: api-service
          uri: lb://api-service
          predicates:
            - Path=/api/sms/**

    # Redis配置
    data:
      redis:
        database: 1
        timeout: 3000ms
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
            max-wait: -1ms

# 日志配置
logging:
  charset:
    console: UTF-8
    file: UTF-8

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    swagger-model-name: 实体类列表
